[refactor] scripts/MountSSH: Modularity and logical fixes
[rm] scripts/Nvidia: Removed
[add] shell/shell_rc: sysstat function
[add] sway/config: playerctl controls

diff --git a/scripts/Watch b/scripts/Watch
--- a/scripts/Watch
+++ b/scripts/Watch
@@ -1,37 +1,58 @@
 #!/usr/bin/env bash
 
-trap 'Exit 0' SIGINT
-trap 'Exit 1' SIGTERM
-
-test $# -eq 0 && {
-    echo "No command or file was given"
-    exit 1
+function LOG() {
+    local type_="$1"; shift
+    case "${type_}" in
+        info)
+            printf '[*]: %s' "$*"
+            ;;
+        warn)
+            printf '[!]: %s' "$*"
+            ;;
+        error)
+            printf '[!!!]: %s' "$*"
+            ;;
+    esac
 }
 
-Exit() {
+function Exit() {
     printf "\n"
     exit $1
 }
 
-time="0.8"
-ARG=""
+function main() {
+    local -a args=("$@")
+    local -a command_=("")
+    local -i time=1 # in seconds
 
-for arg in $@; do
-    if [[ "${arg}" == -* ]]; then
-        case "$arg" in
-            -ex|-e|-x|--ex|--exec)
-                shift; ARG="$1"; shift
-                ;;
-            -t|--time)
-                shift; time="$1"; shift
-                ;;
-        esac
-    fi
-done
+    test $# -ne 0 || LOG error "No command given"
 
-while (true); do
-    clear
-    bash -c "$ARG"
-    sleep "$time"
-done
+    for arg in "${args[@]}"; do
+        if [[ "${arg}" == -* ]]; then
+            case "${arg}" in
+                -t|-*time)
+                    time=${args}
+                    ;;
+                *)
+                    LOG error "Invalid command: '${arg}'"
+                    ;;
+            esac
+        else
+            command_=("${arg}")
+        fi
+    done
+
+    trap 'Exit 0' SIGINT
+    trap 'Exit 1' SIGTERM
+
+    while :; do
+        tput sc          # Save cursor position
+        tput cup 0 0     # Move cursor to the top-left
+        "${command_[@]}" # Run the command again
+        tput rc          # Restore cursor position
+        sleep $time
+    done
+}
+
+main "$@"
 
